version: '3'
services:
  web:
    build: ../
    ports:
      - "5000:5000"
    volumes:
      - .:/home/.
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
